apiVersion: v2
name: cert-manager-webhook-ovh
version: "0.4.0-alpha.0"
description: OVH DNS cert-manager ACME webhook
keywords:
  - cert-manager
  - ovh
  - dns
  - lets-encrypt
  - "Let's Encrypt"
  - tls
  - certificate
  - ssl
home: https://github.com/aureq/cert-manager-webhook-ovh
sources:
  - https://github.com/aureq/cert-manager-webhook-ovh
maintainers:
  - name: Aurélien Requiem
    url: https://github.com/aureq
icon: https://raw.githubusercontent.com/aureq/cert-manager-webhook-ovh/main/assets/images/cert-manager-webhook-ovh.svg
deprecated: false
appVersion: "v0.4.0-alpha0"
