name: release

on:
  push:
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  chart-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: tag-checkout-code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          # # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: tag-package-chart
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p tmp/packages
          helm package --destination tmp/packages/ charts/
          cp charts/Chart.yaml tmp/

      - name: gh-page-checkout-code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
        with:
          ref: 'gh-pages'
          # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
          fetch-depth: 0

      - name: gh-page-configure-git
        shell: bash
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: gh-page-index-chart-repo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          set
          ls -la
          find ./
          cat  .git/config
          git status
          mv tmp/packages/* packages/
          mv tmp/Chart.yaml ./
          helm repo index --url "https://$GITHUB_ACTOR.github.io/$(echo "$GITHUB_REPOSITORY" | cut --delimiter / --fields=2)/packages" .
          git add index.yaml packages/
          git status
          git commit -m "Publish $GITHUB_REF_NAME"
          git push origin gh-pages
